### ISSUE TITLE
tensor size error

### ISSUE THREAD

**Issue by JianshuJie** [txie-93/cgcnn#1]
```
python main.py --train-size 30000 --val-size 10000 --test-size 10000 my_test/mp_test/
Epoch: [0][0/118]	Time 22.182 (22.182)	Data 10.518 (10.518)	Loss 1.0705 (1.0705)	MAE 1.340 (1.340)
Epoch: [0][10/118]	Time 17.675 (19.742)	Data 10.263 (11.007)	Loss 1.0962 (0.9969)	MAE 1.322 (1.234)
Epoch: [0][20/118]	Time 17.326 (19.752)	Data 9.870 (11.245)	Loss 0.7512 (0.9568)	MAE 1.034 (1.198)
Traceback (most recent call last):
  File "main.py", line 488, in <module>
    main()
  File "main.py", line 157, in main
    train(train_loader, model, criterion, optimizer, epoch, normalizer)
  File "main.py", line 208, in train
    for i, (input, target, _) in enumerate(train_loader):
  File "/home/jjs/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 259, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/jjs/gitdir/cgcnn/cgcnn/data.py", line 130, in collate_pool
    torch.cat(batch_nbr_fea, dim=0),
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 12 and 7 in dimension 1 at /pytorch/torch/lib/TH/generic/THTensorMath.c:2897
```

I get mp structure by something like this:
```
from pymatgen.ext.matproj import MPRester
with MPRester(api_key) as m:
    d = m.get_data(mp_id)
    with open(cif_file,'w') as f:
        f.write(d[0]['cif'])
```

**Comment by JianshuJie** [comment]
I find the problem occurs for mp-994911 structure, which is a S8 molecule, so only 7 neighbours are found in this structure while the number is 12 for other structures.
