### ISSUE TITLE
Add CIF module to be installed in the environment in README file

### ISSUE THREAD

**Issue by mairagatti** [txie-93/cgcnn#32]
Traceback (most recent call last):
  File "./main.py", line 22, in <module>
    from cgcnn.data import CIFData
  File "cgcnn/data.py", line 19, in <module>
    from CifFile import ReadCif
ModuleNotFoundError: No module named 'CifFile'

https://github.com/txie-93/cgcnn/blob/master/README.md

**Comment by sayantan1410** [comment]
Hello, I would like to contribute to this issue, can you explain a bit more what I have to do.

**Comment by txie-93** [comment]
@mgdebayser @sayantan1410 Do you both get this error? I don't see this import `from CifFile import ReadCif` in line 19 of data.py
