### ISSUE TITLE
Multiclass classification

### ISSUE THREAD

**Issue by gianmarco-terrones** [txie-93/cgcnn#40]
Thank you for making this tool! I am running into an issue when I run `python main.py --task classification`:

```
/Users/gianmarcoterrones/opt/anaconda3/envs/cgcnn/lib/python3.11/site-packages/pymatgen/io/cif.py:1134: UserWarning: Issues encountered while parsing CIF: Some fractional coordinates rounded to ideal values to avoid issues with finite precision.
  warnings.warn("Issues encountered while parsing CIF: " + "\n".join(self.warnings))
Traceback (most recent call last):
  File "/Users/gianmarcoterrones/Research/cgcnn/main.py", line 513, in <module>
    main()
  File "/Users/gianmarcoterrones/Research/cgcnn/main.py", line 175, in main
    train(train_loader, model, criterion, optimizer, epoch, normalizer)
  File "/Users/gianmarcoterrones/Research/cgcnn/main.py", line 252, in train
    loss = criterion(output, target_var)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gianmarcoterrones/opt/anaconda3/envs/cgcnn/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gianmarcoterrones/opt/anaconda3/envs/cgcnn/lib/python3.11/site-packages/torch/nn/modules/loss.py", line 216, in forward
    return F.nll_loss(input, target, weight=self.weight, ignore_index=self.ignore_index, reduction=self.reduction)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gianmarcoterrones/opt/anaconda3/envs/cgcnn/lib/python3.11/site-packages/torch/nn/functional.py", line 2704, in nll_loss
    return torch._C._nn.nll_loss_nd(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Target 2 is out of bounds.
```

Have I made an error in setting up the customized dataset? Or does the code not currently support multiclass classification? The entries of my id_prop.csv look like this:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/gianmarcoterrones/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/gianmarcoterrones/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

ACOFUU | 1
-- | --
ACOGAB | 1
ACOGEF | 1
ADABAK | 2
AFEJUQ | 1
AGUBUA | 1
AKOXIJ | 1
ALAMUW | 0

</body>

</html>

**Comment by gianmarco-terrones** [comment]
To clarify, the full command I run is `python main.py --task classification --train-ratio 0.6 --val-ratio 0.1 --test-ratio 0.3 root_dir`

**Comment by filipekstrm** [comment]
Realize I am very late, but I think that changing [this line](https://github.com/txie-93/cgcnn/blob/f42ab233c4ee0c416879d6bc2d22a264418413ad/cgcnn/model.py#L118) from ```nn.Linear(h_fea_len, 2)``` to ```nn.Linear(h_fea_len, C)```, where C is the number of classes (in the example data data it seems like C=3) can fix this issue
